name: Check milestone is set up.
on:
  pull_request:
    types: [opened, edited, review_requested]

jobs:
  check_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone
        uses: guillaumevalverde/check_milestone_action@v1.0.13
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}